# Generated by Django 5.0.14 on 2025-11-07 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("birth_date", models.DateField()),
                (
                    "applicant_type",
                    models.CharField(
                        choices=[
                            ("freshman", "Freshman"),
                            ("transferee", "Transferee"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "previous_school",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "credits_earned",
                    models.IntegerField(
                        blank=True, help_text="Number of units completed", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "documents_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="Uploaded documents"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "generated_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="academics.program",
                    ),
                ),
            ],
            options={
                "db_table": "admission_applications",
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="TransfereeCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_code", models.CharField(max_length=50)),
                ("subject_title", models.CharField(max_length=255)),
                ("units", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "grade",
                    models.CharField(
                        help_text="Grade from previous school", max_length=10
                    ),
                ),
                ("credited_date", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credited_subjects",
                        to="admission.admissionapplication",
                    ),
                ),
                (
                    "credited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credited_subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transferee_credits",
                "ordering": ["subject_code"],
            },
        ),
    ]
