# Generated by Django 5.0.14 on 2025-11-07 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionapplication",
            name="processed_by",
        ),
        migrations.RemoveField(
            model_name="admissionapplication",
            name="processed_date",
        ),
        migrations.RemoveField(
            model_name="admissionapplication",
            name="status",
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="needs_registrar_review",
            field=models.BooleanField(
                default=False,
                help_text="Transferee applications need registrar review for TOR validation",
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="generated_user",
            field=models.OneToOneField(
                blank=True,
                help_text="System-generated user account (created automatically)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admission_application",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
