# Generated by Django 5.0.14 on 2025-11-07 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        help_text="e.g. 'Students', 'Grades', 'Terms'", max_length=100
                    ),
                ),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "data_snapshot",
                    models.JSONField(help_text="Full JSON of the original record"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Graduated', 'Term Closed'",
                        max_length=255,
                    ),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "archive",
                "ordering": ["-archived_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "entity_id"], name="archive_entity_7fd8cf_idx"
                    ),
                    models.Index(
                        fields=["archived_at"], name="archive_archive_d6e7f8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="e.g. 'created', 'updated', 'deleted'", max_length=100
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        help_text="e.g. 'Student', 'Grade', 'Section'", max_length=100
                    ),
                ),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                ("old_value_json", models.JSONField(blank=True, null=True)),
                ("new_value_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_trail",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "entity_id"],
                        name="audit_trail_entity_359bdb_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="audit_trail_actor_i_b5aefb_idx",
                    ),
                ],
            },
        ),
    ]
