# Generated by Django 5.0.14 on 2025-11-07 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("SHS", "Senior High School"),
                            ("College", "College"),
                            ("Bachelor", "Bachelor"),
                            ("Masteral", "Masteral"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "passing_grade",
                    models.DecimalField(decimal_places=2, default=3.0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "programs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(help_text="e.g. 'CHED 2021 Rev'", max_length=50),
                ),
                (
                    "effective_sy",
                    models.CharField(help_text="e.g. 'AY 2021-2022'", max_length=20),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curricula",
                        to="academics.program",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Curricula",
                "db_table": "curricula",
                "ordering": ["-effective_sy"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. 'CS101'", max_length=50, unique=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. 'Intro to Computing'", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("units", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "type",
                    models.CharField(
                        choices=[("major", "Major"), ("minor", "Minor")],
                        default="minor",
                        max_length=10,
                    ),
                ),
                (
                    "recommended_year",
                    models.IntegerField(
                        blank=True, help_text="e.g. 1, 2, 3, 4", null=True
                    ),
                ),
                (
                    "recommended_sem",
                    models.IntegerField(
                        blank=True, help_text="1 = 1st sem, 2 = 2nd sem", null=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="academics.program",
                    ),
                ),
            ],
            options={
                "db_table": "subjects",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_level", models.IntegerField()),
                ("term_no", models.IntegerField()),
                ("is_recommended", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_subjects",
                        to="academics.curriculum",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_mappings",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "curriculum_subjects",
                "ordering": ["year_level", "term_no"],
            },
        ),
        migrations.CreateModel(
            name="Prereq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prereq_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_for",
                        to="academics.subject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prerequisite",
                "verbose_name_plural": "Prerequisites",
                "db_table": "prereqs",
                "unique_together": {("subject", "prereq_subject")},
            },
        ),
    ]
