# Generated by Django 5.2.7 on 2025-11-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school_year", models.CharField(max_length=9)),
                (
                    "semester",
                    models.CharField(
                        choices=[("1st", "1st"), ("2nd", "2nd"), ("Summer", "Summer")],
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("school_year", "semester")},
            },
        ),
    ]
