# Generated by Django 5.0.14 on 2025-11-07 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_name",
                    models.CharField(
                        help_text="e.g. 'admission_link_enabled'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "value_text",
                    models.CharField(
                        help_text="e.g. 'true', 'false', '30'", max_length=255
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Optional human note", max_length=255
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="setting_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "settings",
                "ordering": ["key_name"],
            },
        ),
    ]
