# Generated by Django 5.2.7 on 2025-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="sector",
            field=models.CharField(
                choices=[
                    ("SHS", "Senior High School"),
                    ("TVET", "Technical-Vocational Education and Training"),
                    ("COLLEGE", "Higher Education / College"),
                ],
                default="COLLEGE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
