# Generated by Django 5.2.7 on 2025-11-02 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0001_initial"),
        ("subjects", "0002_alter_subject_code_alter_subject_units"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignedsubject",
            name="professor",
        ),
        migrations.RemoveField(
            model_name="section",
            name="professor",
        ),
        migrations.AddField(
            model_name="assignedsubject",
            name="professors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "PROFESSOR"},
                related_name="assigned_subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="professors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "PROFESSOR"},
                related_name="sections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assignedsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_subjects",
                to="subjects.subject",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="code",
            field=models.CharField(max_length=10),
        ),
    ]
