# Generated by Django 5.2.7 on 2025-11-06 11:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Program name (e.g., BSCS, ABM)", max_length=255
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("SHS", "Senior High School"),
                            ("College", "College"),
                            ("Bachelor", "Bachelor"),
                            ("Masteral", "Masteral"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "passing_grade",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.0,
                        help_text="Minimum passing grade for this program",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "db_table": "programs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g., "1st Semester AY 2025-2026"', max_length=50
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "add_drop_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Last day for students to add or drop subjects",
                        null=True,
                    ),
                ),
                (
                    "grade_encoding_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Last day for professors to encode grades",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one term should be active at a time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Term",
                "verbose_name_plural": "Terms",
                "db_table": "terms",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("professor", "Professor"),
                            ("registrar", "Registrar"),
                            ("dean", "Dean"),
                            ("admission", "Admission"),
                            ("admin", "Admin"),
                        ],
                        default="student",
                        help_text="User role determining system access and permissions",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        help_text='Entity type (e.g., "Students", "Grades", "Terms")',
                        max_length=100,
                    ),
                ),
                ("entity_id", models.BigIntegerField(help_text="Original record ID")),
                (
                    "data_snapshot",
                    models.JSONField(
                        help_text="Complete JSON snapshot of the original record"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text='Reason for archiving (e.g., "Term Closed", "Student Graduated")',
                        max_length=255,
                    ),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archive",
                "verbose_name_plural": "Archives",
                "db_table": "archive",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text='Action performed (e.g., "create_enrollment", "update_grade")',
                        max_length=100,
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        help_text='Model/table affected (e.g., "StudentSubjects", "Grades")',
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.BigIntegerField(help_text="ID of the affected record"),
                ),
                (
                    "old_value_json",
                    models.JSONField(
                        blank=True, help_text="Previous values before change", null=True
                    ),
                ),
                (
                    "new_value_json",
                    models.JSONField(
                        blank=True, help_text="New values after change", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Trail",
                "verbose_name_plural": "Audit Trails",
                "db_table": "audit_trail",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text='e.g., "CHED 2021 Rev", "K-12 2016"', max_length=50
                    ),
                ),
                (
                    "effective_sy",
                    models.CharField(
                        help_text='Academic year when this curriculum takes effect (e.g., "AY 2021-2022")',
                        max_length=20,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one curriculum per program should be active at a time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curricula",
                        to="portal.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curriculum",
                "verbose_name_plural": "Curricula",
                "db_table": "curricula",
                "ordering": ["-effective_sy"],
                "unique_together": {("program", "version")},
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_code",
                    models.CharField(
                        help_text='e.g., "CS101-A", "MATH101-B"', max_length=20
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        default=40,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("full", "Full"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={"role": "professor"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "db_table": "sections",
                "ordering": ["section_code"],
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_name",
                    models.CharField(
                        help_text='Setting key (e.g., "admission_link_enabled", "enrollment_open")',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "value_text",
                    models.CharField(
                        help_text='Setting value (e.g., "true", "false", "30")',
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable description of this setting",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "db_table": "settings",
                "ordering": ["key_name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "documents_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Document uploads stored as JSON (e.g., {"tor": "tor.pdf", "id": "id.png"})',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        help_text="Curriculum version assigned to this student",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="portal.curriculum",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="portal.program",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text='Subject code (e.g., "CS101", "MATH101")',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Subject title (e.g., "Introduction to Computing")',
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("major", "Major Subject"),
                            ("minor", "Minor Subject"),
                        ],
                        default="minor",
                        help_text="Major subjects have 6-month INC deadline, Minor subjects have 1-year deadline",
                        max_length=10,
                    ),
                ),
                (
                    "recommended_year",
                    models.IntegerField(
                        help_text="Recommended year level (1-6)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "recommended_sem",
                    models.IntegerField(
                        help_text="Recommended semester (1=1st sem, 2=2nd sem, 3=Summer)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="portal.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "db_table": "subjects",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="StudentSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("inc", "Incomplete"),
                            ("repeat_required", "Repeat Required"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={"role": "professor"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="portal.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_subjects",
                        to="portal.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="portal.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="portal.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Subject",
                "verbose_name_plural": "Student Subjects",
                "db_table": "student_subjects",
                "ordering": ["-created_at"],
                "unique_together": {("student", "subject", "term")},
            },
        ),
        migrations.AddField(
            model_name="section",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="portal.subject",
            ),
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        help_text='e.g., "1.00", "1.75", "2.00", "3.00", "5.00", "INC"',
                        max_length=10,
                    ),
                ),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={"role": "professor"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_record",
                        to="portal.studentsubject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="portal.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "db_table": "grades",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.AddField(
            model_name="section",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="portal.term",
            ),
        ),
        migrations.CreateModel(
            name="Prerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prereq_subject",
                    models.ForeignKey(
                        help_text="Prerequisite subject that must be passed first",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_for",
                        to="portal.subject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject that requires prerequisites",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="portal.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prerequisite",
                "verbose_name_plural": "Prerequisites",
                "db_table": "prereqs",
                "unique_together": {("subject", "prereq_subject")},
            },
        ),
        migrations.CreateModel(
            name="CurriculumSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                (
                    "term_no",
                    models.IntegerField(
                        help_text="1=1st sem, 2=2nd sem, 3=Summer",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "is_recommended",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this subject is recommended for this year/term",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_subjects",
                        to="portal.curriculum",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_mappings",
                        to="portal.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curriculum Subject",
                "verbose_name_plural": "Curriculum Subjects",
                "db_table": "curriculum_subjects",
                "ordering": ["year_level", "term_no"],
                "unique_together": {("curriculum", "subject")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("subject", "term", "section_code")},
        ),
    ]
