# Generated by Django 5.2.7 on 2025-11-06 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="code",
            field=models.CharField(
                default="TEMP",
                help_text="Program code (e.g., BSCS, ABM)",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="lab_hours",
            field=models.IntegerField(
                default=0,
                help_text="Number of lab hours per week",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="lecture_hours",
            field=models.IntegerField(
                default=0,
                help_text="Number of lecture hours per week",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="name",
            field=models.CharField(
                help_text="Program name (e.g., Bachelor of Science in Computer Science)",
                max_length=255,
            ),
        ),
    ]
