# Generated by Django 5.2.7 on 2025-11-06 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portal",
            "0002_program_code_subject_lab_hours_subject_lecture_hours_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="letter_grade",
            field=models.CharField(
                blank=True,
                help_text="Letter grade (e.g., A, B+, C, F)",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="numeric_grade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Numeric grade from 1.00 to 5.00",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="Additional remarks or comments", null=True
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="grade",
            field=models.CharField(
                blank=True,
                help_text='e.g., "1.00", "1.75", "2.00", "3.00", "5.00", "INC"',
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="code",
            field=models.CharField(
                help_text="Program code (e.g., BSCS, ABM)", max_length=20, unique=True
            ),
        ),
    ]
