# Generated by Django 5.2.7 on 2025-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="units",
            field=models.IntegerField(default=3),
        ),
    ]
