# Generated by Django 5.0.14 on 2025-11-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="inc_posted_date",
            field=models.DateField(
                blank=True, help_text="Date when INC grade was given", null=True
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="Additional notes or reasons for grade/changes"
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
